version: "3"

services:
    notification_bot:
        build:
            context: .
            dockerfile: notification/Dockerfile
        volumes:
            - "./notification/notification.log:/notification/notification.log"
        depends_on:
            - mongo

    mongo:
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
        
        volumes:
            - "./mongodb_data:/data/db"
        